### ISSUE TITLE
[Judy] 타입과 추상화 

### ISSUE THREAD

**Issue by Judy-999** [Groot-94/The-Essence-Of-Object-Orientation-Study#10]
1. Swift애서 `enum` 타입 역시 무엇을 추상화했다고 말할 수 있을까요?
2.  103p를 보면 `타입은 추상화다`라고 나와 있습니다. 어떤 행동을 하는가에 관점을 두고 타입으로 추상화해야 한다고 하는데요. `protocol` 역시 추상화라고 생각합니다. 그렇다면 프로토콜을 추상화를 한 번 더 추상화했다고 볼 수 있을까요? <br> 또한 프로토콜로 추상화할 때의 기준은 무엇이 될까요?

**Comment by Groot-94** [comment]
1. Swift애서 enum 타입 역시 무엇을 추상화했다고 말할 수 있을까요?
- enum도 타입을 정의할 수 있기 때문에 추상화 했다고 말할 수 있다고 생각합니다. 하지만 일반적인 추상화 도구와는 다른 방식의 추상화 도구라고 봐야 할 것 같습니다.

2. 103p를 보면 타입은 추상화다라고 나와 있습니다. 어떤 행동을 하는가에 관점을 두고 타입으로 추상화해야 한다고 하는데요. protocol 역시 추상화라고 생각합니다. 그렇다면 프로토콜을 추상화를 한 번 더 추상화했다고 볼 수 있을까요?
또한 프로토콜로 추상화할 때의 기준은 무엇이 될까요?

- 프로토콜도 enum과 같이 조금은 특수한 추상화 도구 라고 생각합니다. 한 번 더 추상화 한다는 의미보단, 어떤 시점에 프로토콜로 추상화 하는지가 중요할 것 같습니다.  구현 시 처음부터 프로토콜로 추상화 할 수 있고, 이미 추상화 된 타입을 그룹화 하기 위해 더 간단하게 추상화 할 수 있다고 생각합니다. 
- 프로토콜로 추상화할 때의 기준은 일반적인 추상화와 동일한 객체의 행동이라고 생각합니다.
