### ISSUE TITLE
[Yeton] 동일한 타입에 속한다는 것의 의미는 무엇일까요?

### ISSUE THREAD

**Issue by yeeton37** [Groot-94/The-Essence-Of-Object-Orientation-Study#11]
책 p.93를 보면 아래와 같이 적혀있습니다.

> 객체의 타입은 객체의 내부 표현과는 아무런 상관이 없다, 따라서 객체의 내부 표현 방식이 다르더라도 어떤 객체들이 동일하게 행동한다면 그 객체들은 동일한 타입에 속한다. 결과적으로 동일한 책임을 수행하는 일련의 객체는 동일한 타입에 속한다고 말할 수 있다.

책임과 행동을 비슷한 맥락으로 볼 때, 저자가 얘기한  객체가 동일하게 행동한다면 동일한 타입에 속한다는 것에 대한 예시를 들어보았습니다.

```swift
class A {
    var coffee: Int = 0
    var 코냐원두: Int = 5
    
    func makeCoffee() {
        코냐원두 -= 2
        coffee += 1
    }
}

class B {
    var coffee: Int = 0
    var 케냐원두: Int = 10
    var 설탕: Int = 5
    
    func makeCoffee() {
        케냐원두 -= 2
        설탕 -= 1
        coffee += 1
    }
}

let 주디카페 = A()
let 예톤카페 = B()
```

위에서 타입 A와 B는 상태는 다르지만, `커피를 만든다`라는 동일한 목적을 가졌기에 동일한 행동을 한다고 볼 수 있을까요?
혹은 행동을 구체화한 메서드 내부의 제조 과정이 다르기 때문에 동일한 행동이라고 볼 수 없는 것일까요?

만약 A와 B가 동일한 행동을 한다고 간주한다면, 이는 A와 B를 동일한 타입, 즉 같은 개념에 속하는 객체로 보는 것이라고 이해했습니다.

**Comment by Judy-999** [comment]
`객체의 내부 표현 방식이 다르더라도 어떤 객체들이 동일하게 행동`이라는 의미가 현재 코드에서 `makeCoffee()` 내부의 구현 방식은 달라도 `커피를 만든다`라는 동일한 행동을 하는 것과 같다고 생각합니다.

앨리스 예제에서 정원사 트럼프와 여왕 트럼프를 하나의 트럼프 타입으로 정의했듯이, 현재는 A와 B가 다른 타입처럼 보이지만 `CoffeeShop`이라는 하나의 타입으로 추상화할 수 있어 보입니다. 

A와 B로 분리된 타입을 `CoffeeShop`이라는 하나의 타입으로 분류하므로써 얻을 수 있는 이점이 바로 추상화를 해야 하는 이유인 것 같습니다.
