### ISSUE TITLE
[SooKoong] 일반화와 추상화 비교

### ISSUE THREAD

**Issue by Jeon-Minsu** [Groot-94/The-Essence-Of-Object-Orientation-Study#14]
p127 쪽에는 다음의 내용이 언급되고 있습니다.
> 객체의 타입과 역할 사이에는 일반화/특수화 관계가 성립하는 것이 일반적이다.
> 일반화/특수화 관점에서 좀 더 일반적인 개념을 의미하는 역할은 일반화이며 구체적인 개념을 의미하는 객체의 타입은 특수화다.
> 역할이 협력을 추상적으로 만들수 있는 이유는 역할 자체가 객체의 추상화이기 때문이다.

여기서 역할과 객체의 타입을 일반화/특수화 관계에 보통 속하며, 역할과 객체의 관계를 추상화의 관계로 보고 있습니다.

그렇다면, 일반화와 추상화는 같은 것인지, 그렇지 않다면 어떤 차이가 있는지를 알아보고, 객체와 객체의 타입의 차이도 같이 고민해봅시다.

**Comment by yeeton37** [comment]
1. 일반화는 추상화를 위한 도구라고 생각합니다. 예시로 책에서 `병사,신하,왕자와 공주, 왕과 왕비`를 `트럼프`라는 개념으로 묶은 것은 개별 객체 간의 차이점은 무시하고 공통점을 취한 것입니다. 이는 추상화의 도구중 하나인 일반화를 한 것이라고 생각했습니다!


- 즉, `일반화 == 추상화를 위한 도구` 입니다.

2. `객체의 타입`을 `일반화`한 것이 `역할`이라고 볼 수 있는가? 라는 주제로 대화를 나눴습니다.          결론은 왕1과 왕비1, 신하1와 병사1(객체)를 각각 왕이라는 객체의 타입, 왕비라는 객체의 타입 등으로 추상화할 수 있고, 또 이를 협력이라는 문맥에서 볼 때 트럼프라는 역할로 한번 더 묶어 추상화하는 것이 가능하다고 생각했습니다. 
- 따라서 일반화(추상화)를 한번 하냐, 아니면 한번 추상화를 하고 또 한번 더 트럼프라는 역할로 추상화하냐의 차이는 있지만 결국 `객체의 타입을 추상화한 것`이 `역할`이라는 결론을 내렸습니다!
