### ISSUE TITLE
[Yeton] 공용 인터페이스란 무엇일까요?

### ISSUE THREAD

**Issue by yeeton37** [Groot-94/The-Essence-Of-Object-Orientation-Study#15]
책 p.117
> 객체의 책임을 이야기할 때는 일반적으로 외부에서 접근 가능한 공용 서비스의 관점에서 얘기한다.
> 즉, 책임은 객체의 외부에 제공해줄 수 있는 정보(아는 것의 측면)와 외부에 제공해줄 수 있는 서비스(하는 것의 측면)의 목록이다. 따라서 책임은 객체의 공용 인터페이스를 구성한다. 공용 인터페이스의 개념은 객체지향의 중요한 원리 중 하나인 캡슐화로 이어진다.

1. 위에서 얘기하는 외부에 제공해줄 수 있는 정보와 외부에 제공해줄 수 있는 서비스란 어떤 걸 의미할까요? (외부에 제공이라는 말 뜻 자체가 이해가 잘 안갑니다. 단순 private/public 이런걸 의미하는 건가요?)
2. 객체의 공용 인터페이스가 무엇일까요?
3. 공용 인터페이스는 왜 캡슐화에 중요한 역할을 하는 걸까요? private이 붙지 않은 메서드나 프로퍼티를 공용 인터페이스라고 부르는 건지..!

책을 보다가 잘 이해가 안된 부분입니다
같이 얘기해보면 좋을 것 같습니다

**Comment by Groot-94** [comment]
몰루
