### ISSUE TITLE
[Sookoong] 프로시저란 무엇인가?

### ISSUE THREAD

**Issue by Jeon-Minsu** [Groot-94/The-Essence-Of-Object-Orientation-Study#18]
책의 p149를 보면, 메서드와 관련하여 프로시저라는 개념이 등장하였습니다.

> 객체지향 프로그래밍 언어에서 메서드는 클래스 안에 포함된 함수 또는 프로시저를 통해 구현된다.
> 프로시저 호출에 대한 실행 코드를 컴파일 시간에 결정하는 절차적인 언어와 확연히 구분되는 특징이다.

1. 먼저, 프로시저란 무엇인지를 알아봅시다.
2. 절차지향의 개념과 객체지향과의 차이점을 공부해봅시다.
3. 다음으로, swift에서 프로시저를 찾아볼 수 있는지 얘기해봅시다.
4. xcode의 lldb에서 po를 입력하고 엔터를 치면, 1, 2, 3.. 등 숫자가 나오며 코드를 한 줄, 한 줄 입력할 수 있는데 이또한 프로시저에 해당하는 것인지 고민해봅시다.

**Comment by yeeton37** [comment]
1. 프로시저란 `특정 작업을 위한 쿼리들의 블록`이라고도 볼 수 있고, 혹은 그냥  `하나의 절차`라고 볼 수도 있을 것 같아요. 

>프로시저와 함수의 차이점
- 프로시저: 특정 작업을 수행하며, 리턴값을 가질수도 안가질수도 있고, 서버단에서 기술한다.
- 함수: 특정 계산을 수행, 리턴값을 반드시 하나만 가지고, 무조건 가져야하고, 화면단에서 기술

2. 절차지향과 객체지향의 핵심적인 차이점은 절차지향은 순차적으로 실행되는 것에 초점을 둔 것이고, 객체지향은 객체간의 관계에 초점을 둔 것이라고 생각합니다.

>절차지향(Procedural Programming) 특징과 장단점
- 대표적인 예로는 C언어가 있습니다.
- 객체지향보다 속도가 빠름
- 장점
       - 컴퓨터의 처리구조와 유사해 실행속도가 빠릅니다.
- 단점
       - 유지보수가 어렵습니다.
       - 실행 순서가 정해져 있으므로 코드의 순서가 바뀌면 동일한 결과를 보장하기 어렵습니다.
       - 디버깅이 어렵습니다.
 
> 객체지향(Object Oriented Programming)의 특징과 장단점
- 대표적인 예로는 java, swift가 있습니다.
- 장점
       - 코드의 재활용성이 높습니다.
       - 코딩이 절차지향보다 간편합니다.
       - 디버깅이 쉽습니다.
- 단점
       - 처리속도가 절차지향보다 느립니다.
       - 설계에 많은 시간소요가 들어갑니다.

3. 프로시저를 `하나의 절차`라는 개념으로 생각한다면, 객체지향과 절차지향은 반대되는 개념이 아니기 때문에 객체지향에서도 프로시저가 당연히 자연스럽게 사용된다고 생각했습니다.
4. 3번과 마찬가지로  순차적인 접근이기에 프로시저로 볼 수 있을 것 같습니다.
