### ISSUE TITLE
[Groot] 책임이 자율적일수록 적절하게 추상화되며, 응집도가 높아지고, 결합도가 낮아지며, 캡슐화가 증진되고, 인터페이스와 구현이 명확이 분리되며, 설계의 유연성과 재사용성이 향상된다. 라는 말의 의미

### ISSUE THREAD

**Issue by Groot-94** [Groot-94/The-Essence-Of-Object-Orientation-Study#19]
저는 5장에서 `"책임이 자율적일수록 적절하게 추상화되며, 응집도가 높아지고, 결합도가 낮아지며, 캡슐화가 증진되고, 인터페이스와 구현이 명확이 분리되며, 설계의 유연성과 재사용성이 향상된다."` 라는 말을 이해하는게 가장 중요하다고 생각합니다.

저 말의 의미를 고민해보고 정리해보면 좋겠다고 생각이 들었습니다.

1. 자율적인 책임이란?
2. 책임이 자율적일수록 적절하게 추상화된다.
3. 책임이 자율적일수록 응집도가 높아진다.
4. 책임이 자율적일수록 결합도가 낮아진다.
5. 책임이 자율적일수록 캡슐화가 증진된다.
6. 책임이 자율적일수록 인터페이스와 구현이 명확이 분리된다.
7. 책임이 자율적일수록 설계의 유연성과 재사용성이 향상된다.

**Comment by Judy-999** [comment]
연산을 하는 메시지를 예시로 들면 이해가 쉬울 것 같습니다.

**1. 자율적인 책임**
자율적인 책임은 책임을 수행하는 방식에 자유를 주는 것입니다. 
연산된 값을 얻고 싶을 때는 `연산하라`라고 메시지를 보내면 수신자가 어떻게 연산을 하는지 신경쓰지 않는 것이 자율적인 책임을 부여한 것입니다. 만약 그렇지 않다면 `더하기 해라`, `빼기 해라`, `곱해라` 이런 식으로 메시지를 보내 연산의 로직을 정해주는건 자율적이지 못하다고 볼 수 있습니다. 이런 관점에서 책임을 너무 작게 주지 않는 것으로도 표현할 수 있습니다.

**2. 추상화**
책임이 자율적이면 어떤 책임, 어떤 역할을 가진 객체(타입)인지 명확해집니다. 위 예시에서 보면 자유롭게 연산을 수행할 수 있는 객체는 `연산을 할 수 있는 타입`으로 추상화가 가능하게 됩니다.

**3. 높은 응집도 / 4. 결합도**
우선 응집도는 `한 모듈 내부의 처리 요소들이 서로 관련되어 있는 정도`이고 결합도는 ` 서로 다른 모듈 간에 상호 의존하는 정도`입니다.

`연산해라`라고 자율적인 책임을 주었을 때는 객체 내부의 메서드를 자유롭게 호출해서 연산을 할 수 있어 응집도가 올라가게 됩니다. 
또한 `더하기 해라`, `빼기 해라`, `곱해라` 라고 메시지를 보내면 송신자와 수신자의 결합도가 올라가게 되는데 `연산하라` 하나의 메시지로만 수행하면 결합도가 낮아지게 됩니다.

**5. 캡슐화**
캡슐화는 필요한 행위만 보여주고 실제 구현 내용은 외부로부터 감추는 것을 말합니다.
`연산해라`만 보여주면 실제 내부에서 더하기, 빼기, 곱하기가 이뤄지는 구현부는 외부로부터 은닉할 수 있어 캡슐화가 증진됩니다.

**6. 인터페이스와 구현**
캡슐화와 비슷하게 자율적인 책임을 부여하는 메시지들을 인터페이스로 사용하면 내부 구현을 위한 코드와 구분할 수 있습니다.

**7. 설계의 유연성과 재사용성**
`연산하라`라고 메시지를 보내면 수신자가 상황과 조건에 따라 다양한 방식으로 처리할 수 있습니다. 처리의 다양성은 곧 유연성이 되고, 여러 조건을 처리할 수 있으므로 여러 상황에서 재사용이 가능하게 됩니다.

즉 연산이 필요한 여러 객체들이 해당 메시지를 이용할 수 있게 됩니다.
