### ISSUE TITLE
[SooKoong] 기능 측면 설계의 장점

### ISSUE THREAD

**Issue by Jeon-Minsu** [Groot-94/The-Essence-Of-Object-Orientation-Study#21]
책의 p180, 181을 살펴보면 다음의 내용을 발견할 수 있었습니다.

> ... 기능이 아니라 구조를 기반으로 모델을 구축하는 편이 좀 더 범용적이고 이해하기 쉬우며 변경에 안정적이라는 것이다.
> 모든 소프트웨어 제품의 설계에는 두 가지 측면이 존재한다.
> 하나는 '기능(function)' 측면의 설계이고, 다른 하나는 '구조(structure)' 측면의 설계다.

이후에도, 책에서는 구조 측면 설계, 정확히는 안정적인 객체 구조를 바탕으로 시스템 기능을 객체 간의 책임으로 분배하는 
'객체지향' 프로그래밍의 장점을 살펴볼 수 있었습니다.
그렇다면 반대의 경우, 즉 기능 측면 설계를 하였을 때의 장점으로는 무엇이 있을지 알아보는 시간을 가져봅시다.

**Comment by Groot-94** [comment]
기능 측면 설계의 명확한 장점은 객체체지향의 단점이라고 볼 수 있을 것 같습니다.
1. 객체들의 협력을 이용해 구현하지 않고 단순하게 요구하는 기능을 구현하기 위한 설계이기 때문에 단순하다.
2. 단순하기 때문에 비용이 적게든다.
