### ISSUE TITLE
[Judy] 도메인 모델의 가역성

### ISSUE THREAD

**Issue by Judy-999** [Groot-94/The-Essence-Of-Object-Orientation-Study#22]
205 페이지에 다음과 같은 내용이 나옵니다.

> 객체 지향의 장점은 도메인을 모델링하기 위한 기법과 도메인을 프로그래밍하는 기법이 동일하다는 점이다.
> 도메인 모델링에서 사용한 객체와 개념을 프로그래밍 설계에서 객체와 클래스로 변환할 수 있다. = **연결 완전성**
> 
> 연결 완전성의 역방향 역시 성립한다. = **가역성**
> 코드의 변경으로부터 도메인 모델의 변경사항을 유추할 수 있다.

모델을 보고 코드로 구현하는 것이 `연결 완전성`, 코드의 변화를 통해 모델의 변화를 알 수 있는 것이 `가역성`이라고 이해했습니다.
객체 지향에서 위 성격을 가질 수 있는 이유나 특성은 무엇일까요?

또한 이는 객체지향 이전의 개발 방법은 대부분 대응하지 못한다고 하는데 그 이유는 무엇일지 생각해봅시다.

**Comment by Jeon-Minsu** [comment]
도메인 모델은 간단히 설명하면 실세계의 사물을 기반으로 소프트웨어 객체로 식별한 구조이고, 이를 코드의 영역에서 구현을 하였을 때, 객체지향 방식에서는 표현적 차이가 적기 때문에 각 영역에서의 변경 사항을 인지하기 수월할 것입니다.
즉, 도메인 모델과 코드가 동일한 모델링 패러다임을 공유하고 있기 때문에 도메인 모델에서의 변화이든, 코드의 변화이든 표현적(의미적) 차이가 적어 해당 변경사항을 다른 영역으로 변환하여 이해하는 작업이 쉽기 때문에 연결 완전성, 가역성의 특징을 가질 수 있었습니다. 

반면, 객체지향 이전의 개발 방법은 도메인 모델을 코드로 변환하는 과정에서 결국 객체라는 구조가 존재하지 않아, 기능 중심으로 구현되어 있을 것으로 예상됩니다.
이때문에 도메인 모델을 온전히 아우르기 보다는, 기능에 치우쳐 표현할 수 밖에 없을 것 같습니다.
