### ISSUE TITLE
[Yeton] 도메인모델과 클래스 다이어그램의 차이?

### ISSUE THREAD

**Issue by yeeton37** [Groot-94/The-Essence-Of-Object-Orientation-Study#24]
저는 처음에 도메인모델이 클래스 다이어그램과 비슷한 구조라고 생각했습니다.

그런데 다시 개념을 읽어보니 도메인모델 == 멘탈모델, 즉 사람들의 마음속에 구축되는 모델이라고 하더라구요.
그렇다면 도메인모델은 실체가 없는, 그저 마음속이나 머리속으로 그려본 현상의 흐름이고, 
이를 도식화한 것이 p.191에 나타나있는 도식화 된 도메인 모델이라고 이해했습니다.

그렇다면 실제로 저희가 많이 그려봤던 클래스 다이어그램은 도메인 모델과 어떤 상관관계를 가질 수 있을까요?
또한 도메인모델과 클래스 다이어그램을 구현하는 순서는 어떻게 되는 것이 자연스러울까요?

**Comment by Judy-999** [comment]
클래스 다이어그램과 구조(생김새)는 비슷해 보일 수 있지만,
클래스 다이어그램은 클래스 간의 관계를 나타내고, 도메인 모델은 실제 프로그램의 대상들 간의 관계를 나타낸다고 할 수 있습니다.

도메인 모델은 실세계와 밀접하고 클래스 다이어그램은 코드와 더 가깝다고 생각합니다.

도메인 모델은 실세계를 은유할 수 있는 `은행`, `예금`과 같은 대상이 포함된다면 클래스 다이어그램은 해당 대상들을 구현한 객체들과 더불어 기능을 위한 (예를 들어 `JsonParser`) 클래스들도 포함될 수 있습니다.

그렇기 때문에 도메인 모델을 기반으로 먼저 구현한 후 클래스 다이어그램을 구성하는 순서가 자연스러워 보입니다.
