### ISSUE TITLE
[Sookoong] 인터페이스와 구현의 분리

### ISSUE THREAD

**Issue by Jeon-Minsu** [Groot-94/The-Essence-Of-Object-Orientation-Study#25]
책의 p228에 따르면, 소제목부터 `인터페이스와 구현을 분리하라`로 소개되어,
> 명세 관점과 구현 관점을 분리하는 것은 매우 중요하다
> 캡슐화를 위반해서 구현을 인터페이스 밖으로 노출해서도 안 되고, 
인터페이스와 구현을 명확하게 분리하지 않고 흐릿하게 섞어놓아서도 안 된다

이를 바탕으로, 
1. 아래의 다이어그램은 인터페이스와 구현이 명확히 분리된 것일까요?
2. 그렇지 않다면 어떠한 방식으로 인터페이스와 구현을 분리할 수 있을까요?
3. 또한, ISP는 인터페이스가 응집력 측면에서 작게 분할하여 클래스가 필요한 작업만 실행하도록 하는 것을 목표로 하여, 단일 책임 원칙(SRP)과 비슷해 보이는데, 어떠한 차이가 있을지 논의해봅시다.

![image](https://user-images.githubusercontent.com/99063327/205473792-53ba0f27-fbdf-46af-b298-4ec7e175ba35.png)

---

출처: https://yoongrammer.tistory.com/99

**Comment by Groot-94** [comment]
1. 아래의 다이어그램은 인터페이스와 구현이 명확히 분리된 것일까요?
>
2. 그렇지 않다면 어떠한 방식으로 인터페이스와 구현을 분리할 수 있을까요?
3. 또한, ISP는 인터페이스가 응집력 측면에서 작게 분할하여 클래스가 필요한 작업만 실행하도록 하는 것을 목표로 하여, 단일 책임 원칙(SRP)가 비슷해 보이는데, 어떠한 차이가 있을지 논의해봅시다.

**Comment by Groot-94** [comment]
부록: iOS에서의 대표적인 SRP위반 사례
1.ViewController

   - Massive ViewController

   - MVP, MVVM, VIPER

2. ViewController가 SRP를 위반하고 있다고 판단하는 근거는?

   - Provides ther infrastructure for managing the views of yours UIKit app.
