### ISSUE TITLE
[Groot] 클래스의 안정적인 측면과 불안정한 측면

### ISSUE THREAD

**Issue by Groot-94** [Groot-94/The-Essence-Of-Object-Orientation-Study#26]
책 228.p에는 `명세 관점은 클래스의 안정적인 측면을 드러내야 한다. 구현 관점은 클래스의 불안정한 측면을 드러내야 한다.` 라고 나와있습니다.

1. 여기에서 말하는 클래스의 안정적인 측면과 불안정한 측면이란 어떻게 이해할 수 있을까요?
2. 명세 관점, 구현 관점과 클래스의 두 가지 측면과 어떤 관계가 있을까요?

**Comment by Jeon-Minsu** [comment]
LGTM
