### ISSUE TITLE
[Yeton] 도메인 개념이 무엇일까요?

### ISSUE THREAD

**Issue by yeeton37** [Groot-94/The-Essence-Of-Object-Orientation-Study#27]
7장에서 파울러는 객체지향 설계 안에 존재하는 세가지 관점의 방향으로 클래스를 바라보아야 한다고 말합니다. 
여기서 개념 관점, 명세 관점, 구현 관점이 나오는데 여기서`개념 관점`에 대한 정의가 명확히 이해가 되지 않습니다. 

p.207
>개념 관점에서 설계는 도메인 안에 존재하는 개념과 개념들 사이의 관계를 표현한다. 

p.227
>메시지를 수신할 객체를 선택하는 방법중 첫 번째 전략은 도메인 개념 중에서 가장 적절한 것을 선택하는 것이다.
>소프트웨어 클래스가 도메인 개념을 따르면 변화에 쉽게 대응할 수 있다.
 
위에서 말하는 `도메인 개념`이란 무엇을 의미하는 걸까요?

**Comment by Judy-999** [comment]
p.185
`프로그램을 사용하는 대상 분야를 도메인이라고 한다`에서 도메인은 프로그램과 관련된 **대상**들로 볼 수 있습니다.

p.211
`객체지향의 관점에서 커피 전문점이라는 도메인은 손님 객체, 메뉴 항목 객체, 메뉴판 객체, 바리스타 객체, 커피 객체로 구성된 작은 세상이다.`
여기서 도메인은 객체들의 모음으로 볼 수 있습니다.

p.89
`타입은 개념이다.`라고 나와있습니다.
도메인 개념에서 개념은 타입으로 생각할 수 있고, 객체는 타입의 인스턴스로 볼 수 있습니다.

---

위 내용을 종합하면 `도메인`이란 해당 `프로그램과 관련된 타입들의 모음과 관계`이라고 정의할 수 있습니다.
