### ISSUE TITLE
[Judy] 설계 순서와 객체의 개수

### ISSUE THREAD

**Issue by Judy-999** [Groot-94/The-Essence-Of-Object-Orientation-Study#28]
<br>1. 
208 페이지 세 번째 문단에서 `... 개념 관점, 명세 관점, 구현 관점의 순서대로 소프트웨어를 개발한다는 의미처럼 들릴 수도 있지만 이것은 사실이 아니다.`
하지만 209 페이지에서 `도메인 모델에서 시작해서 최종 코드까지의 구현 과정을 간략하게 설명`하겠다고 하고 실제로 뒷 내용은 그렇게 진행됩니다. 
205 페이지에서 `개념 관점에서 설계는 도메인 안에 존재하는 개념과 개념들 사이의 관계를 표현한다`라고 되어 있으니 사실상 `개념 -> 명세 -> 구현`의 순서로 설계가 이뤄진다고 생각해도 무방할까요? 아니라면 어떤 순서가 좋을지, 순서라는게 아예 존재하지 않을지 이야기해보면 좋겠습니다.
<br>2. 
커피 전문점 예시는 물론 설명하기 위해 작성된 것을 감안해야겠지만 개인적으로 바리스타 객체가 메뉴판을 직접 들고 있는 것은 어떨까 생각했습니다.

```java
class Barista {
    private List<MenuItem> items;
// private var items: [MenuItem]

// 커피 만드는 메서드

// 메뉴 이름으로 커피 메뉴를 골라 주는 메서드
}
```

이런 식으로 하면 바리스타의 책임은 더 많아지지만 객체(Mene)를 하나 줄일 수 있습니다. 객체를 줄이면 연관도 같이 없어진다고 볼 수 있을 것 같은데 작게 쪼개서 객체는 많이 가지지만 객체와 객체들의 관계를 얕고 넓게 표현하는 것이 더 좋은 방법일까요? 그렇다면 이유는 무엇일까요?

**Comment by yeeton37** [comment]
1.  저자가 `개념 관점, 명세 관점, 구현 관점의 순서대로 소프트웨어를 개발한다는 의미처럼 들릴 수도 있지만 이것은 사실이 아니다.`라고 말한 것은 이 순서대로 하지 말라는 것이 아니라 어떤 한 클래스를 이 세가지 방향으로 각각 바라볼 수 있어야함을 강조한 것 같아요. 저도 설계를 한다면 도메인 개념들을 살펴보는 개념 -> 인터페이스 구조를 짜는 명세 -> 세부 코드 구현의 순서로 설계를 할 것 같습니다...! 다만 꼭 이 순서를 지켜서 하라는 뜻이 아니라는 말같네요!
2. 바리스타 객체가 메뉴판을 직접 들고 있는 것도 이 상황에서는 좋은 방법 같아요. 그런데 확장성을 생각해보면 메뉴판도 그 자체의 객체가 되어야 바리스타와 연관이 없는 곳에서도 독립적으로 사용될 수 있지 않을까요? 여러 확장성을 생각해보고 그때그때 상황에 맞게 설계하면 될 것같습니다!
