### ISSUE TITLE
[Judy] 각 객체는 책임을 수행하는 방법을 자율적으로 선택할 수 있다는 의미는 무엇일까요?

### ISSUE THREAD

**Issue by Judy-999** [Groot-94/The-Essence-Of-Object-Orientation-Study#3]
28p에 커피 주문 예시에서 `책임을 수행하는 방법은 자율적으로 선택할 수 있다`라는 설명이 나옵니다.

요청을 받은 사람은 요청을 처리하는 방법을 자유롭게 선택할 수 있다고 하며 바리스타는 자신의 독특한 방법으로 커피를 만들 수 있다고 예시를 듭니다. 이를 `다형성`이라는 능력으로 설명합니다.

다형성의 정의를 위키피디아에서 살펴보니 다음과 같습니다.
>프로그램 언어의 각 요소들(상수, 변수, 식, 오브젝트, 함수 메서드 등)이 다양한 자료형(type)에 속하는 것이 허가되는 성질

제가 알고 있기로 다형성을 구현하는 방법에는 오버로딩(overloading), 오버라이딩(overriding)이 있습니다. 

의문이 드는 것은 `요청을 받은 사람은 요청을 처리하는 방법을 자유롭게 선택할 수 있다` 인데 오버로딩이나 오버라이딩이나 요청하는 쪽에서 이미 선택하는 것이 아닐까 생각이 들었습니다. 

`객체`가 책임을 수행하는 방법을 선택할 수 있다는 것은 어떤 의미일까요?

**Comment by Jeon-Minsu** [comment]
한 명의 바리스타가 커피를 만드는 방법이 다양함을 의미하는 것이 아니라, 바리스타 자격증을 가진 사람들은 저마다의 방식으로 커피를 만들 수 있음을 의미합니다. 즉, 요청을 받은 사람들이 요청을 처리하는 방법을 자유롭게 선택할 수 있다는 의미는 하나의 메서드 안에서 구현을 다양하게 한다는 의미가 아니라, 동일한 요청을 받더라도 역할을 수행할 수 있는 서로 다른 유형의 객체들마다 별도의 방식으로 요청을 처리할 수 있음을 의미합니다.
