### ISSUE TITLE
[SooKoong] 메서드와 책임, 나아가 책임과 행동은 동일한가?

### ISSUE THREAD

**Issue by Jeon-Minsu** [Groot-94/The-Essence-Of-Object-Orientation-Study#4]
객체지향의 사실과 오해 책 27 ~ 29 페이지의 역할과 책임을 정리하면 다음과 같습니다.

> 객체는 다른 객체와 협력하는 과정에서 특정한 역할을 부여받는다.

> 역할은 의미적으로 책임이라는 개념을 내포하여, 하나의 객체가 여러 책임을 부여받음을, 역할을 부여받았다는 의미로 이해할 수 있다.

그리고, 책의 32페이지에서 다음의 내용이 있습니다.

> 객체를 상태(state)와 행동(behavior)을 함께 지닌 실체라고 정의한다.

이를 정리해보면, 객체는 상태와 행동을 함께 지닌 실체로, 여러가지 책임이 종합한 역할을 수행하고 있다고 판단합니다.

그렇다면, 실제 프로그래밍 과정에서 구현한 함수, 즉 메서드를 책임과 동일한 의미로 이해하는 것이 바람직한 것인지, 그렇지 않다면 책임과 행동을 서로 다른 것으로 이해한 것 같은데, 각각 어떻게 구분하는 것이 적절한지에 대하여 고민해봅시다.

**Comment by Judy-999** [comment]
우선 객체는 여러 책임을 통해 부여받은 역할을 합니다.

책임과 행동은 다른 의미를 가지는데 어떤 책임들이 있다면 그 책임이 수행되는 것이 행동이라고 생각합니다.
결론적으로 메서드는 책임보다는 행동에 가깝고, 그 메서드를 수행함으로써 책임을 다하게 됩니다.

`책임 = 객체가 처리해주어야 할 일`
메서드로 이해하자면 메서드 자체가 책임이 아닌, 책임을 수행한다는 의미로 해석할 수 있습니다.

프로토콜과 같이 내부 구현 내용은 없는 메서드가 선언되어 있는 상태는 곧 프로토콜을 채택하면 해당 메서드를 구현해야 함을 의미하기에 책임으로 볼 수 있습니다.

책임과 행동을 구분하는 예시로 연극을 들 수 있습니다. 예를 들어 [로미오와 줄리엣]이라는 연극에서 줄리엣 역할을 맡았을 때,
"귀족 같아야 한다", "관객의 몰입을 끌어낸다"와 같은 책임이 있다면,  대사를 하고, 연기를 하는 행위는 `행동`을 통해 책임을 수행할 수 있습니다.
