### ISSUE TITLE
[Yeton] 동등성과 동일성은 무슨 차이가 있을까요?

### ISSUE THREAD

**Issue by yeeton37** [Groot-94/The-Essence-Of-Object-Orientation-Study#5]
책 p.58
>동등성은 상태를 이용해 두 값이 같은지 판단할 수 있는 성질이다. 
>동일성은 식별자를 기반으로 객체가 같은지를 판단할 수 있는 성질이다.

책에서는 위와 같이 동등성과 동일성을 설명하고 있습니다.

그렇다면 동등성과 동일성을 활용할 수 있는 예시는 무엇이 있을까요?

**Comment by Jeon-Minsu** [comment]
동등성을 활용한 예시는 값의 비교를 해본 경험이 많을 것으로 예상이 되어 생략합니다.
동일성을 활용한 예시는 참조 객체가 같은 인스턴스인지를 확인하는 경우에 많이 사용될 것으로 판단됩니다.
그 예시로, 아래와 같이 싱글톤 인스턴스에 대하여 같은 싱글톤인지를 확인하는 경우에는 동일한 식별자(주소값)를 가지고 있기 때문에
비교를 함에 있어 true 값을 반환하지만, 
각각의 참조 객체를 인스턴스화하였을 때는,  서로 다른 식별자를 가지고 있기 때문에, 동일한 객체이지 않아 비교 결과, false 값을 반환합니다.

```swift
class A {
    let aa = Singleton.shared
    let aaa = Singleton()
}

class B {
    let bb = Singleton.shared
    let bbb = Singleton()
}

class Singleton {
    static let shared = Singleton()

    init () {}
}

let classA = A()
let classB = B()

print(classA.aa === classB.bb) // return true
print(classA.aaa === classB.bbb) // return false
```
