### ISSUE TITLE
[Judy] 프로퍼티와 객체의 자율성

### ISSUE THREAD

**Issue by Judy-999** [Groot-94/The-Essence-Of-Object-Orientation-Study#8]
1. '정적'인 프로퍼티와 '동적'인 프로퍼티 값은 무엇을 의미하는 걸까요?

2. `객체 지향의 세계에서 객체는 다른 객체의 상태에 직접적으로 접근할 수도, 상태를 변경할 수도 없다.`라고 51p에 나와있습니다. <br> 다른 언어에서는 불가할 수 있지만 Swift에서는 다른 객체의 프로퍼티에 직접 접근이 가능하다고 생각합니다. <br> <br> 외부 객체가 직접적으로 객체의 상태를 변경하거나 조회할 수 없으므로 `행동`이 등장한다고 하는데요. 행동은 메서드라고 생각합니다.<br><br>  `객체는 스스로의 행동에 의해서만 상태가 변경되는 것을 보장함으로써 객체의 자율성을 유지한다.`라고 나와있는데, <br> 그렇다면 Swift의 객체는 자율성이 낮다고 볼 수 있을 까요? 오히려 객체의 역할과 책임이 다양하다고 생각할 수 있을까요?

3. 상태를 먼저 결정하고 행동을 나중에 결정하는 방법은 설계에 나쁜 영향을 끼친다고 합니다. <br>여러 분들도 설계할 때 메서드를 먼저 생각하시는 편인가요? 상태를 먼저 결정할 경우 캡슐화가 저해되는 이유는 무엇일까요?

**Comment by Judy-999** [comment]
1. 정적인 프로퍼티는 프로퍼티 그 자체이고, 동적인 프로퍼티는 각각의 프로퍼티 값이라고 생각합니다. <br> 예를들어 `Person`이라는 객체의 `name`과 `gender`라는 프로퍼티는 추후에 변경 수정되지 않아 정적지만, `name`의 값 자체는 변경할 수 있으므로 동적입니다.

2. `객체는 스스로의 행동에 의해서만 상태가 변경되는 것을 보장함으로써 객체의 자율성을 유지한다.` -> `객체는 스스로의 행동에 의해서만 상태가 변경되는 것을 보장"하도록 해서" 객체의 자율성을 "유지해라"`라고 해석할 수 있겠습니다. <br><br>상태에 직접 접근하고 변경 가능하더라도 반드시 필요한 상황이 아닌 이상 프로퍼티는 `private`을 통해 은닉화를 하고 객체 내부에서만 접근 및 수정을 할 수 있도록 구현하여 자율성을 높이도록 지향해야 합니다.

3. 상태를 먼저 설계하면 설계 자체가 상태 중심으로 흘러 많은 프로퍼티와 적은 메서드로 구현될 수 있다고 생각합니다. 비록 실제 구현할 때는 프로퍼티부터 구현하는 경우가 다반사이지만, 최대한 메서드 먼저 그리고 메서드를 중심을 구현하려고 노력하면 최소한의 프로퍼티만 가지게 하고 내부 메서드로만 프로퍼티를 변경하게 하여 은닉화에 도움이 될 것 같습니다. 또한 메서드 즉 행도 주심으로 설계되어 캡슐화에 도움이 될 것 같습니다!

**Comment by Jeon-Minsu** [comment]
1. 프로퍼티 자체는 선언 이후, 생성, 수정, 삭제가 불가능하기 때문에, 정적인 속성을 보이고, 프로퍼티 값 자체는 함수(행동)를 통해 충분히 변경 가능한 값이기 때문에, 동적인 프로퍼티 값으로 정의를 내린 것 같습니다.

2. 해당 이슈는 Swift를 객체의 관점에서 보았기 때문에 발생한 문제라고 생각합니다. 객체의 관점에서 한 객체의 상태 변경은, 그 객체의 행동을 통해서만 변경되어야 하기 때문에, 외부에서 다른 객체의 상태 자체에 접근을 하면 안되지만, 실제 Swift에서 다른 객체의 프로퍼티에 접근이 가능합니다. 이는, 객체지향의 관점에서 바라본 것이기 때문에, 위에서 말씀해주신 것처럼 구현해야 함을 당부하는 것이지, 다른 관점에서는 충분히 프로퍼티에 접근하는 것이 당연한 이슈일 수도 있다는 생각이 듭니다.

3. 설계를 할 때, 주로 상태를 먼저 결정하고, 행동을 나중에 결정했던 것 같습니다. 이는 결국에는 객체 간의 협력을 저해할 수도 있기 때문에, 위에서 말씀하신 방법을 명심하여 설계하고자 노력할 것입니다. 상태를 먼저 결정한 경우 캡슐화가 저해되는 이유는 이미 상태를 외부에서 변경하면, 이를 보완하기 위한 행동은 필요가 없어지기에, 이렇게 진행되면 결국 상태만을 은닉화하야 하는데, 은닉화를 하면 외부에서 접근을 할 수 없으니, 결국 캡슐화를 할 수 없을 것입니다.

**Comment by yeeton37** [comment]
1. 정적인 프로퍼티는 변경되지 않고 고정되는 프로퍼티를 의미하기 때문에 앨리스를 예시로 들면 키, 위치, 음료 등이 앨리스의 정적인 프로퍼티라고 할 수 있다고 해요. 동적인 프로퍼티는 시간이 흐름에 따라 변경되기 때문에 위에서 얘기한 키, 위치, 음료의 변할 수 있는 "값"을 의미하는 것 같습니다!

2. `객체는 스스로의 행동에 의해서만 상태가 변경되는 것을 보장함으로써 객체의 자율성을 유지한다.` 말 자체에 자율성이 내포되어 있다고 생각해요. 다른 객체는 해당 객체에 접근할 수 없기 때문에 해당 객체 내에 상태와 행동이 모두 집약되어 있기 때문에 객체 스스로 내부 상태를 변경할 수 있는 자율성이 커질 수 있다고 생각합니다.

3. 저는 보통 설계할 때 프로퍼티를 먼저 생각하고 짰던 것 같습니다. 상태를 먼저 결정할 경우 
 1) 상태가 객체 내부로 깔끔하게 캡슐화되지 못하고 공용 인터페이스에 그대로 노출된 확률이 높아지고
 2) 상태를 먼저 고려한 방식은 협력이라는 문맥에서 벗어난 채 설계를 하게 될 가능서이 높아진다

위와 같은 이유로 캡슐화가 저해될 수 있다고 책에 나와있고 이에 동감합니다!

**Comment by Groot-94** [comment]
1. 정적 프로퍼티는 객체가 가지고 있는 프로퍼티 그 자체를 의미한다고 생각합니다. 동적 프로퍼티는 정적 프로퍼티가 가지고 있는 "데이터"라고 생각합니다. 

2. 책에서 나오는 `외부 객체는 스스로의 행동에 의해서만 상태가 변경되는 것을 보장함으로써 객체의 자율성을 유지한다. ` 라는 의미는 개발언어 그 자체에서 객체를 구성하는 방법을 의미하는게 아니라 **실제로 객체지향을 구현하는 코드(객체)에서 자율성을 유지할 수 있도록 해야한다.** 라는 의미로 느껴집니다. 그런 부분은 `swift에서 은닉화, 캡슐화를 통해 외부 객체가 직접적으로 상태를 변경하는 것을 막을 수 있기 때문에 swift는 자율성이 낮다고 하기엔 어렵다고 생각합니다.`

3. 저의 생각은 `설계하는 시점에서 행동 -> 상태 라는 순서로 생각을 해야한다.` 라고 느꼈습니다. 그런의미에서 실제로 구현하는 시점에는 순서에 상관이 없다고 생각했습니다.
캡슐화를 저해한다는 의견은 아직 잘 모르겠습니다.
